runtime: nodejs10
handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    secure: always
    upload: build/static/js/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    secure: always
    upload: build/static/css/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    secure: always
    upload: build/static/media/(.*)
  - url: /(.*\.(json|ico))$
    static_files: build/\1
    secure: always
    upload: build/.*\.(json|ico)$
  - url: /
    static_files: build/index.html
    secure: always
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    secure: always
    upload: build/index.html